version: '3'
name: yasitan

services:
  mongodb:
    image: mongo:6
    ports:
      - '27417:27017'
    volumes:
      - ./mongodb:/data/db

  api:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    environment:
      - PORT=3000
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_TOKEN_LIFETIME_SECONDS=${JWT_TOKEN_LIFETIME_SECONDS}
      - JWT_SECRET=${JWT_SECRET}
      - APP_MONGODB_URI=${APP_MONGODB_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

    image: yasitan/api
    ports:
      - '3100:3000'
    command: nx serve backend
    depends_on:
      - mongodb

  webapp:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    image: yasitan/webapp
    ports:
      - '4200:4200'
    command: nx serve webapp

volumes:
  root-node_modules: null
