version: '3.1'
name: yasitan

services:
  nm:
    build:
      context: ./
      dockerfile: ./node-modules.dockerfile
    command: pnpm i
    volumes:
      - ./node_modules:/app/node_modules

  mongodb:
    image: mongo:6
    ports:
      - '27417:27017'
    volumes:
      - ./mongodb:/data/db

  api:
    build:
      context: ./
      dockerfile: ./server-ts.development.dockerfile
    environment:
      - PORT=3000
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_TOKEN_LIFETIME_SECONDS=${JWT_TOKEN_LIFETIME_SECONDS}
      - JWT_SECRET=${JWT_SECRET}
      - APP_MONGODB_URI=${APP_MONGODB_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

    image: yasitan/api
    volumes:
      - ./:/app
    ports:
      - '3100:3000'
    command: nx serve backend
    depends_on:
      nm:
        condition: service_completed_successfully
      mongodb:
        condition: service_started

  webapp:
    build:
      context: ./
      dockerfile: ./server-ts.development.dockerfile
    image: yasitan/webapp
    volumes:
      - ./:/app
    ports:
      - '4200:4200'
    command: nx serve webapp
    depends_on:
      nm:
        condition: service_completed_successfully
