version: '3.1'
name: yasitan

services:
  nm:
    build:
      context: ./
      dockerfile: ./node-modules.dockerfile
    volumes:
      - ./node_modules:/app/node_modules

  mongodb:
    image: mongo:6
    ports:
      - '27417:27017'
    volumes:
      - ./mongodb:/data/db

  api:
    build:
      context: ./apps/backend
      dockerfile: ../../server-ts.development.dockerfile
    environment:
      - PORT=3000
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_TOKEN_LIFETIME_SECONDS=${JWT_TOKEN_LIFETIME_SECONDS}
      - JWT_SECRET=${JWT_SECRET}
      - APP_MONGODB_URI=${APP_MONGODB_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

    image: yasitan/api
    volumes:
      - ./apps/backend:/app
      - ./node_modules:/app/node_modules
    ports:
      - '3000:3000'
    command: npm run start api
    # command: nx serve backend
    depends_on:
      # - nm
      - mongodb

  webapp:
    build:
      context: ./apps/webapp
      dockerfile: ../../server-ts.development.dockerfile
    image: yasitan/webapp
    volumes:
      - ./webapp:/app
      - ./node_modules:/app/node_modules
    ports:
      - '8080:3000'
    command: nx serve webapp
    # depends_on:
      # - nm
