// import '../../app/globals.css';

import { setUser, useProfileDispatch } from '@/contexts/profile';
import type { Metadata } from 'next';
import { useEffect, useState } from 'react';
import { getField } from '@/lib/local-storage';
import { getCurrentUser } from '@/integrations/api';
import If from '../shared/if';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [render, setRender] = useState(false);
  const profileDispatch = useProfileDispatch();
  useEffect(() => {
    new Promise(resolve => {
      if (getField('access-token')) {
        getCurrentUser()
          .then(user => {
            setUser(profileDispatch, user);
          })
          .catch(() => {})
          .finally(() => resolve(undefined));
      } else {
        resolve(undefined);
      }
    }).then(() => {
      setRender(true);
    });
  }, []);

  return (
    <If condition={render} else={<>Loading...</>}>
      {children}
    </If>
  );
}
